export const robotFramework = [
  {
    id: "brain",
    no: "01",
    label: "大模型与任务规划",
    english: "COGNITION",
    summary: "把视觉、深度、点云和语言输入转换为语义理解、任务拆解、长程规划与动作意图。",
    detail: "重点比较 VLM / VLA、世界模型、端到端策略、数据闭环，以及模型是否形成可验证的真实任务能力。",
  },
  {
    id: "control",
    no: "02",
    label: "运动控制与执行",
    english: "MOTION CONTROL",
    summary: "承接高层意图，完成状态估计、步态、平衡、全身控制、轨迹规划与力位混合控制。",
    detail: "重点比较训练—仿真—实机链路、实时控制接口、触觉与力控能力，以及异常情况下的安全降级。",
  },
  {
    id: "body",
    no: "03",
    label: "机械结构",
    english: "EMBODIMENT",
    summary: "通过形态、自由度、执行器、传动、传感器、末端、载荷和防护能力定义任务边界。",
    detail: "双足、四足与纯轮式面向不同任务，不用单一参数排序，而是判断结构能否支撑目标场景。",
  },
];

export const robotCompanies = [
  {
    id: "unitree",
    index: "01",
    name: "宇树科技",
    english: "UNITREE",
    focus: "足式本体与开放运控生态",
    morphologies: ["双足", "四足"],
    hero: "/assets/robot/unitree-g1-product.png",
    secondary: "/assets/robot/unitree-go2-cutout.png",
    railImage: "/assets/robot/unitree-g1-cutout.png",
    summary: "以高性能腿足本体、较低二次开发门槛和强化学习工具链形成产品优势，双足与四足产品密度高。",
    strength: "从 Isaac Gym / RSL-RL 训练、MuJoCo Sim2Sim 到实机部署的路径清晰，SDK2 提供底层状态与控制接口。",
    boundary: "未形成纯轮式产品线；默认任务规划模型与商用底层控制器的公开细节有限，平台算力不能直接替代任务成功率。",
    brain: {
      title: "UnifoLM-WMA-0 / VLA-0",
      copy: "WMA-0 通过世界模型预测机器人与环境的后续状态，并为动作策略提供物理交互信息；VLA-0 则面向通用人形操作，把视觉与语言指令转换为动作。",
      evidence: "两条路线均来自宇树官方公开页面：WMA-0 对应 G1-D 数据与训练方案，VLA-0 已列入官方开源项目。",
    },
    control: {
      title: "RL Gym → Sim2Sim → Real",
      copy: "Go2、G1、H1 与 H1-2 可在官方 RL Gym 中训练，再经 Play / MuJoCo 校验后部署到实机。G1 支持力位混合，Dex3-1 可选触觉。",
      evidence: "优势集中在腿足运动控制与开发生态，实际控制频率、安全限值和量产策略需按 SDK 版本核对。",
    },
    body: "G1 / G1 EDU 站立高度约 1320 mm、整机约 35 kg，基础版 23 个关节电机，EDU 版本可扩展至 43 个；双足产品之外，A2 与 Go2 分别覆盖工业和消费级四足任务。",
    products: ["H2", "G1 EDU", "A2", "Go2"],
    endEffectors: [
      {
        kind: "灵巧手",
        name: "Dex3-1",
        image: "/assets/robot/unitree-dex3.png",
        spec: "三指 7 主动自由度｜710 g｜单手 33 个触觉传感器",
        compatibility: "宇树官方明确说明 Dex3-1 可与 G1 配合使用；G1 EDU 参数页同时列出力控三指灵巧手和可选触觉阵列。",
        sourceLabel: "Dex3-1 官方产品页",
        sourceUrl: "https://www.unitree.com/cn/mobile/Dex3-1/",
      },
    ],
    sources: [
      ["G1 官方参数", "https://www.unitree.com/mobile/g1/"],
      ["G1-D 与 WMA-0", "https://www.unitree.com/mobile/G1-D/"],
      ["官方开源项目", "https://www.unitree.com/mobile/opensource/"],
    ],
  },
  {
    id: "agibot",
    index: "02",
    name: "智元机器人",
    english: "AGIBOT",
    focus: "三形态覆盖与数据模型工具链",
    morphologies: ["双足", "四足", "纯轮式"],
    hero: "/assets/robot/agibot-a2-official-3.png",
    secondary: "/assets/robot/agibot-quadruped-cutout.png",
    railImage: "/assets/robot/agibot-a2-official-3.png",
    summary: "产品覆盖双足、四足与轮式移动操作，并通过 AgiBot World、Genie Sim / Studio、AimRT 与灵渠 OS 连接数据、仿真、模型和机器人。",
    strength: "GO-2 Action CoT 将低频语义规划和高频动作跟随拆成异步双系统，适合长程任务与实时运动并行。",
    boundary: "不同 SKU 的传感器、算力、末端和模型默认能力差异较大，不能把平台能力直接视为每台量产机的标准配置。",
    brain: {
      title: "GO-2 Action CoT",
      copy: "低频 System 2 负责语义理解、任务分解与推理，高频 System 1 负责连续动作跟随；GO-1 则以 VLM、潜在动作规划器与动作专家组成。",
      evidence: "AgiBot World 与 Genie 工具链补充数据生成、仿真和训练闭环，但具体机型需逐项确认模型和算力配置。",
    },
    control: {
      title: "高频动作系统与力控",
      copy: "A3 将主数据单元与人机交互单元分开部署，并开放运动控制仿真与高层接口；X2 Ultra 提供 URDF，支持 Isaac Gym 与 MuJoCo，面向二次开发和动作验证。",
      evidence: "控制能力需要按具体机型与软件版本核对，A3 v3.0 与 X2 Ultra 的开放接口范围并不相同。",
    },
    body: "远征 A3 身高约 173 cm、净重约 55 kg，颈部 2、双臂 7×2、双腿 6×2、腰部 3 个主动自由度，手部可选灵动款 2026 或专业款 2026；精灵 G1 / G2 则以轮式底盘承载双臂操作任务。",
    products: ["远征 A3", "灵犀 X2 Ultra", "绝尘 D1 Ultra", "精灵 G1 / G2"],
    endEffectors: [
      {
        kind: "灵巧手",
        name: "OmniHand 2025",
        image: "/assets/robot/agibot-omnihand-closeup.png",
        spec: "16 总自由度 / 10 主动自由度｜≤500 g｜触觉版 400+ 感知点",
        compatibility: "标准化 USB、RS485 与 CAN-FD 接口；官方列出可适配智元 X2、A2 及同类人形机器人，X2 Ultra 页面明确支持选配 OmniHand。",
        sourceLabel: "OmniHand 官方产品页",
        sourceUrl: "https://store.agibot.com/products/omnihand-2025",
      },
      {
        kind: "A3 手部选配",
        name: "灵动款 2026 / 专业款 2026",
        imageAvailable: false,
        visualLabel: "A3 官方手部配置",
        spec: "灵动款 4×2 DoF｜专业款 13×2 DoF",
        compatibility: "这两种名称与自由度来自远征 A3 v3.0 官方开发文档；官方文档未提供可独立核验的产品图，因此页面不使用其他机器人或 OmniHand 图片代替。",
        sourceLabel: "A3 v3.0 官方开发文档",
        sourceUrl: "https://open.agibot.com/docs/aimdk/a3/v3_0/dev_guide/01-a3_overview",
      },
    ],
    sources: [
      ["A3 v3.0 官方文档", "https://open.agibot.com/docs/aimdk/a3/v3_0/dev_guide/01-a3_overview"],
      ["A2 Ultra 官方产品页", "https://store.agibot.com/products/a2-ultra"],
      ["X2 系列官方产品页", "https://store.agibot.com/collections/humanoid-robot"],
    ],
  },
  {
    id: "deep",
    index: "03",
    name: "云深处科技",
    english: "DEEP ROBOTICS",
    focus: "复杂地形与工业防护闭环",
    morphologies: ["双足", "四足", "轮足边界"],
    hero: "/assets/robot/deep-dr02-body.jpg",
    secondary: "/assets/robot/deep-x30-cutout.png",
    railImage: "/assets/robot/deep-dr02-cutout.png",
    summary: "围绕复杂地形运动、工业防护与巡检救援形成差异化优势，双足 DR02 与四足 X30 均强调宽温、防护和工程部署。",
    strength: "官方强化学习工具链覆盖 Lite3、M20 与 DR02；DeepVLA 1.0 面向开放词汇语义导航和多楼层场景。",
    boundary: "现有证据更能支撑语义导航、复杂地形和工业感知，通用双臂操作大模型与生产级控制器的公开信息较少。",
    brain: {
      title: "DeepVLA 1.0",
      copy: "把语义点云与大语言模型结合，用自然语言驱动跨室内、室外与楼层的导航；工业方案采用端侧小模型和云端大模型协同。",
      evidence: "公开能力主要落在开放词汇导航与工业巡检，不应直接外推为通用双臂 VLA 操作能力。",
    },
    control: {
      title: "Isaac Lab 与 RSL-RL",
      copy: "Lite3、M20 与 DR02 使用官方强化学习训练链路，模型可通过 ONNX 部署到实机；DR02 引入 AMP 运动先验。",
      evidence: "运动控制证据覆盖多类腿足产品，量产控制器的频率、故障降级与接触控制细节仍需项目级确认。",
    },
    body: "DR02 采用拟人双足结构，整机达到 IP66，并可在 -20℃ 至 55℃环境运行；小臂、整臂和整腿支持模块化快拆更换。X30 则以四足结构面向巡检、消防与复杂地形任务。",
    products: ["DR02", "DR01", "X30", "Lite3", "M20"],
    endEffectors: [],
    sources: [
      ["DR02 官方产品页", "https://www.deeprobotics.cn/robot/index/dr02.html"],
      ["X30 官方产品页", "https://www.deeprobotics.cn/en/index/product.html"],
    ],
  },
  {
    id: "galbot",
    index: "04",
    name: "银河通用",
    english: "GALBOT",
    focus: "轮式移动操作与垂直产品化",
    morphologies: ["纯轮式"],
    hero: "/assets/robot/galbot-g1-product.png",
    secondary: "/assets/robot/galbot-g1.png",
    railImage: "/assets/robot/galbot-g1-product.png",
    summary: "聚焦纯轮式移动操作，利用全向底盘、长臂展、双臂、长续航和快速换电服务零售与工业任务。",
    strength: "GraspVLA 以十亿级合成动作数据、自动回归感知和 Flow Matching 支持开放词汇抓取，并通过 SDK 暴露全身规划与导航接口。",
    boundary: "不覆盖双足和四足形态；内部伺服实现、长程任务成功率与复杂动态环境下的生产指标公开有限。",
    brain: {
      title: "GraspVLA",
      copy: "依托 SynGrasp-1B 十亿级合成动作数据，以自动回归感知和 Flow Matching 生成动作，重点解决开放词汇、零样本与少样本抓取。",
      evidence: "大模型路线与轮式移动操作场景匹配度高，长程任务表现仍需结合真实业务流程和成功率指标判断。",
    },
    control: {
      title: "全身多链规划",
      copy: "SDK 提供关节与笛卡尔控制、IK / FK、约束优化、轨迹、原始传感器、碰撞检测、SLAM 和动态避障接口。",
      evidence: "轮式底盘与双臂协同是核心，小脑层通过全身规划承接 VLA / RL 动作，不以腿足动态平衡为目标。",
    },
    body: "Galbot G1 高约 1730 mm、重约 92.5 kg，机身含 21 个驱动关节（不计末端执行器），全向轮式底盘支持原地转向，双臂总载荷 10 kg，满电运行时间约 8 小时。",
    products: ["Galbot G1", "Galbot S1"],
    endEffectors: [
      {
        kind: "末端形式示意",
        name: "平行夹爪 / 电动吸盘",
        image: "/assets/robot/galbot-end-effectors.png",
        imageAlt: "平行夹爪与电动吸盘结构示意",
        spec: "双臂单臂载荷 5 kg、合计 10 kg｜支持多种末端切换",
        compatibility: "图示用于清楚区分夹爪与吸盘两种末端形式，不代表独立型号外观。G1 官方规格和 SDK 示例均列出左右夹爪与左右吸盘控制。",
        sourceLabel: "Galbot G1 官方产品页",
        sourceUrl: "https://www.galbot.com/g1",
      },
    ],
    sources: [
      ["Galbot G1 官方产品页", "https://www.galbot.com/g1"],
      ["Galbot G1 SDK", "https://developer.galbot.com/docs/SDK/1.7.0/g1/zh/examples_python/"],
    ],
  },
];

export const robotMorphologies = [
  {
    id: "biped",
    label: "双足人形",
    image: "/assets/robot/unitree-biped-cutout.png",
    imageAlt: "宇树双足人形机器人代表产品",
    strength: "动态平衡与类人空间适配",
    scenarios: "楼梯、窄通道、人类工位与需要类人操作高度的任务。",
    cost: "控制复杂、能耗高，对跌倒保护、关节冗余和实时全身控制要求最高。",
    examples: "H2 / G1 EDU / A3 / X2 / DR02",
  },
  {
    id: "quadruped",
    label: "四足机器人",
    image: "/assets/robot/agibot-quadruped-cutout.png",
    imageAlt: "智元四足机器人代表产品",
    strength: "越障、防护与载荷稳定性",
    scenarios: "复杂地形、工业巡检、应急救援、室外运输与危险区域作业。",
    cost: "操作能力通常依赖外挂机械臂，狭窄人类工位与精细双臂任务不是结构强项。",
    examples: "A2 / Go2 / D1 Ultra / X30 / Lite3",
  },
  {
    id: "wheeled",
    label: "纯轮式移动操作",
    image: "/assets/robot/galbot-g1-product.png",
    imageAlt: "银河通用 G1 纯轮式移动操作机器人完整产品形象",
    strength: "导航效率、续航与双臂工作空间",
    scenarios: "零售拣选、仓储搬运、工业上下料和结构化室内长时间作业。",
    cost: "台阶、碎石和非结构化地形通过性有限，对场地连续性和导航基础设施依赖更强。",
    examples: "精灵 G1 / G2 / Galbot G1 / S1",
  },
];

export const robotComparisonRows = {
  coverage: [
    ["形态覆盖", "双足、四足", "双足、四足、纯轮式", "双足、四足、轮足边界", "纯轮式"],
    ["核心定位", "腿足本体与开放运控", "全形态与全栈工具链", "复杂地形与工业防护", "轮式移动操作与垂直落地"],
    ["代表产品", "H2 / G1 / A2 / Go2", "A3 / X2 / D1 / 精灵 G1/G2", "DR02 / X30 / M20", "Galbot G1 / S1"],
    ["适合优先验证", "腿足运动、科研与二开", "跨形态产品组合与工具链", "巡检、救援与复杂地形", "零售、仓储与工业移动操作"],
  ],
  intelligence: [
    ["大模型与任务规划", "UnifoLM-WMA-0 / VLA-0", "GO-2 Action CoT：低频语义规划与高频动作系统", "DeepVLA：语义点云与语言模型导航", "GraspVLA：自动回归感知与 Flow Matching"],
    ["运动控制与执行", "模仿学习 / 强化学习；Isaac Gym → MuJoCo → 实机", "高频 System 1；RL、阻抗与力控", "Isaac Lab + RSL-RL；ONNX 实机部署", "IK / FK、全身规划、SLAM、避障与实时直通"],
    ["公开证据", "官方仓库、SDK2 与 RL Gym", "GO-2 技术、GO-1 论文、X1 开源", "DeepVLA 与官方 RL 工具链", "SDK 手册、GraspVLA 与 SynGrasp-1B"],
    ["仍需项目验证", "默认任务规划模型与商用控制细节", "各 SKU 默认能力与安全限值", "通用操作 VLA 与量产控制细节", "长程生产指标与内部伺服实现"],
  ],
  structure: [
    ["执行结构", "高扭矩腿足关节；可选灵巧手", "双足 / 四足 / 全向轮式；多类末端", "腿足关节、宽温与工业防护", "全向底盘、长臂展、双臂与模块化末端"],
    ["感知与算力", "深度、3D 激光雷达与可选 Orin", "RGB-D、多 RGB、雷达、力矩；Orin / RK3588", "激光雷达、深度、广角与最高 275 TOPS 配置", "立体视觉、多 RGB、腕部深度、力传感、雷达与 AGX Orin"],
    ["续航与维护", "G1 约 2 h；A2 空载约 5 h", "约 2 h 至 4 h+；部分支持换电", "DR02 换电；X30 约 2.5–4 h", "G1 / S1 约 8 h；S1 双电池快换"],
    ["工程化重点", "开发门槛和运动生态", "平台覆盖和配置组合", "IP66 / IP67、宽温与救援", "续航、载荷、工作空间和任务闭环"],
  ],
};

export const robotProducts = [
  ["宇树", "H2", "双足", "31 DOF / 约 70 kg", "腿关节峰值 360 Nm；单臂额定约 7 kg", "高动态人形本体"],
  ["宇树", "G1 EDU", "双足", "23–43 DOF / 约 35 kg+", "Dex3-1 可选触觉；深度相机 + 3D 激光雷达", "科研、数据采集与二次开发"],
  ["宇树", "A2", "四足", "12 DOF / 约 42 kg", "持续行走载荷约 25 kg；IP56；空载约 5 h", "工业运输与复杂地形"],
  ["宇树", "Go2", "四足", "12 DOF / 约 15 kg", "4D 激光雷达 + 广角相机；约 1–2 h", "消费、教育与开发"],
  ["智元", "远征 A3", "双足", "约 173 cm / 55 kg", "颈2、双臂7×2、双腿6×2、腰3；手部可选灵动款或专业款；续航10 h", "通用人形与操作"],
  ["智元", "灵犀 X2 Ultra", "双足", "30 DOF / 约 39 kg", "3D 雷达、RGB-D、多 RGB；RK3588×2 + Orin NX", "轻量人形与交互"],
  ["智元", "绝尘 D1 Ultra", "四足", "12 DOF / 约 16 kg", "最高 3.7 m/s；IP54；可选雷达 / 深度 / 5G", "巡检、教学与开发"],
  ["智元", "精灵 G1", "纯轮式", "20 主动 DOF / 约 150 kg", "三组 RGB-D、五组鱼眼、六维力、AGX Orin；4 h+", "移动操作与商业服务"],
  ["云深处", "DR02", "双足", "拟人结构 / 模块化快拆", "IP66；-20–55℃；小臂、整臂和整腿支持快拆更换", "工业人形与复杂环境"],
  ["云深处", "X30", "四足", "约 56 kg", "融合感知与导航；2.5–4 h；IP67；-20–55℃", "巡检、消防与救援"],
  ["云深处", "M20", "轮足边界", "轮足结构", "官方 RL 工具链覆盖；强调通过性和移动效率", "工业巡检与运输"],
  ["银河通用", "Galbot G1", "纯轮式", "机身 21 DOF / 约 92.5 kg", "立体视觉、多 RGB、腕部深度、六维力、AGX Orin；约 8 h", "零售拣选与移动操作"],
  ["银河通用", "Galbot S1", "纯轮式", "机身 17 DOF / 约 320 kg", "单臂 15 kg、双臂 30 kg；双电池快换；约 8 h", "工业上下料与重载操作"],
];

export const robotProductImages = {
  "宇树-H2": "/assets/robot/thumb-unitree-h2.png",
  "宇树-G1 EDU": "/assets/robot/thumb-unitree-g1.png",
  "宇树-A2": "/assets/robot/thumb-unitree-a2.png",
  "宇树-Go2": "/assets/robot/thumb-unitree-go2.png",
  "智元-远征 A3": "/assets/robot/thumb-agibot-a3.png",
  "智元-灵犀 X2 Ultra": "/assets/robot/thumb-agibot-x2.png",
  "智元-绝尘 D1 Ultra": "/assets/robot/thumb-agibot-d1.png",
  "智元-精灵 G1": "/assets/robot/thumb-agibot-g1.png",
  "云深处-DR02": "/assets/robot/thumb-deep-dr02.png",
  "云深处-X30": "/assets/robot/thumb-deep-x30.png",
  "云深处-M20": "/assets/robot/thumb-deep-m20.png",
  "银河通用-Galbot G1": "/assets/robot/thumb-galbot-g1.png",
  "银河通用-Galbot S1": "/assets/robot/thumb-galbot-s1.png",
};

export const robotConclusions = [
  ["宇树科技", "腿足运动与开发生态", "需要高动态本体、强化学习验证和较低二次开发门槛的团队"],
  ["智元机器人", "多形态产品与数据、仿真、模型协同工具链", "需要在多形态产品中复用数据、仿真和模型能力的项目"],
  ["云深处科技", "复杂地形、工业防护与纵向闭环", "面对巡检、救援、宽温和高防护环境的工业项目"],
  ["银河通用", "轮式移动操作与垂直产品化", "关注长续航、双臂工作空间和零售 / 工业任务闭环的场景"],
];
